### ISSUE TITLE
Public key objects not supported

### ISSUE THREAD

**Issue by slindal** [hzlmn/aiohttp-jwt#108]
In some cases a json web token format of the public key is needed and the public key is then an object. In the below case an RSA key object from the cryptography package. aiohttp-jwt currently insists on the key being a string. The easy and most obvious way to fix it is to remove the check in the JWTMiddleware init function that checks if it is a string. 

jwt = {'e': 'AQAB',
          'kty': 'RSA',
          'n': 'iurr_T41t8oWtMfet8CBWpZp5vCJX9KfsH9gEljgDa4DPQXAdUb5ZkbQE2if-LcXKBGn00sD7YNFViyK92yZsTNUzihju4-u0Yo8ztpf7ypmh...'}

public_key = jwt.algorithms.RSAAlgorithm.from_jwk(json.dumps(js))

def verify_jwt(token):
    return jwt.decode(token, key=public_key, audience="audience")

**Comment by hzlmn** [comment]
Hi, why is it problematic to serialize key like ?
```python
serialized = public_key.public_key().public_bytes(
    cryptography.hazmat.primitives.serialization.Encoding.PEM, 
    cryptography.hazmat.primitives.serialization.PublicFormat.SubjectPublicKeyInfo,
) # receive bytes here
``` 
Allowing passing arbitrary object is not a good api practice..especially in future i plan to add library agnostic way to decode so `pyjwt` want be a strict requirement.

**Comment by slindal** [comment]
@hzlmn thank you this does indeed work. Strange because the byte key that I generated the jwk from did not work.  Sorry for the noise.
