### ISSUE TITLE
Send token /login 

### ISSUE THREAD

**Issue by Nenad7955** [hzlmn/aiohttp-jwt#127]
Hey, I'm trying to understand how the thing works, and it would be really cool, and useful for newer programmers if you could write a small documentation, maybe link to key words etc. Also would be amazing if you'd make a small example where /login: returns the token to the user.

**Comment by hzlmn** [comment]
Hi, this library provides only middleware for processing requests with JWT token and small permission helpers. It does not provide functionality for login and obtaining token, if i got your question right.

**Comment by Nenad7955** [comment]
I see, I guess i got a bit confused with the @login_required

**Comment by hzlmn** [comment]
As login mechanism vary from project to project it is hard to come with good unified solution for all flows. But you can try `aiohttp-security` or `aiohttp-login` for your needs to provide user auth facilities.

**Comment by hzlmn** [comment]
https://steelkiwi.com/blog/jwt-authorization-python-part-1-practise/ 
may be helpful

**Comment by hzlmn** [comment]
Closing for now, feel free to re-open if necessary.

**Comment by Nenad7955** [comment]
Yeah, I read the code, good work, Thank you! And thanks for the tips!
