### ISSUE TITLE
non-Bearer token schema

### ISSUE THREAD

**Issue by vikitikitavi** [hzlmn/aiohttp-jwt#14]
## Your environment:
 - Python version: 3.6
 - Operating System: Ubuntu 16.04

## Problem description

I'm not sure it is an issue or not.
With the *credentials_required=False* flag, the client is allowed to send the non-**Bearer** token schema.

## Steps to reproduce
Run the login_required.py.
Make a request:

```bash
$ curl \
--header "Authorization: InvalidSchema eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXIwIn0.-zSBJbSBFhESOcrfPCzHkoHIMJ653jcBcUwodNR0Ko8"\
localhost:8080/protected
```

**Comment by hzlmn** [comment]
Yes it is an issue. Would you like to send a pr? Fix is easy.
