### ISSUE TITLE
RuntimeError if the handler with check_permissions in the separate file

### ISSUE THREAD

**Issue by wkomor** [hzlmn/aiohttp-jwt#144]
Hi everyone!

I'm trying to use check_permissions decorator. 

While I'm following the example https://github.com/hzlmn/aiohttp-jwt/blob/master/example/permissions.py everything is good. 

But when I put my handler into the separate file I'm getting an exception:

`RuntimeError: ('Incorrect usage of decorator.', 'Please initialize middleware first')`

It seems caused by check ` if middleware._request_property is ...: ` in the decorator code.

**Comment by hzlmn** [comment]
Hello, could you show how do you initialize middlware and use decorator?
Generally speaking, your middleware should be initialized before decorator as they used shared property name.

**Comment by wkomor** [comment]
I have initialized the middlware by following:
main.py:
```
import jwt
from aiohttp import web

from aiohttp_jwt import JWTMiddleware

from handler import protected_handler

sharable_secret = "secret"


async def get_token(request):
    return jwt.encode(
        {"username": "johndoe", "scopes": ["username:johndoe"]}, sharable_secret
    )


jwt_middleware = JWTMiddleware(
    sharable_secret,
    token_getter=get_token,
    request_property="user",
    credentials_required=True,
    whitelist=[r"/public*"],
)


async def public_handler(request):
    return web.json_response(
        {
            "username": request["user"].get("username")
            if "user" in request
            else "anonymous"
        }
    )


app = web.Application(middlewares=[jwt_middleware])


app.router.add_get("/public", public_handler)
app.router.add_get("/protected", protected_handler)

if __name__ == "__main__":
    web.run_app(app)
```

handler.py
```
from aiohttp import web
from aiohttp_jwt import check_permissions, match_any


@check_permissions(["app/user:admin", "username:johndoe"], comparison=match_any)
async def protected_handler(request):
    return web.json_response({"username": request["user"].get("username")})
```

**Comment by hzlmn** [comment]
Thanks for reporting, made a minor fix. `v0.6.1` is already available.
