### ISSUE TITLE
Unable validate secret if secret is cert in der x509

### ISSUE THREAD

**Issue by pecheneg12** [hzlmn/aiohttp-jwt#154]
I use: 
cert = load_der_x509_certificate(base64.b64decode(config['jwt']['secret']), backend)
secret = cert.public_key()
app = web.Application(
		middlewares = [JWTMiddleware(
				secret,
				algorithms = config['jwt']['algorithms'],
				audience = config['jwt']['audience'],
				issuer = config['jwt']['issuer']
			)]
	)
But raise on check secret: 
if not (secret_or_pub_key and isinstance(secret_or_pub_key, str)):
        raise RuntimeError(
            'secret or public key should be provided for correct work',
        )
If i disable this check, my token work correctly.
How i can validate token if secret in der-509 ?

**Comment by hzlmn** [comment]
Hello, just serialize your key like 
```python
serialized = public_key.public_key().public_bytes(
    cryptography.hazmat.primitives.serialization.Encoding.PEM, 
    cryptography.hazmat.primitives.serialization.PublicFormat.SubjectPublicKeyInfo,
) # receive bytes here
```
Also take a look on a similar issue https://github.com/hzlmn/aiohttp-jwt/issues/108 i made a statement there why passing object directly not good imho.

**Comment by pecheneg12** [comment]
Package from pip doesn't have this patch. Thanks about this!
