### ISSUE TITLE
Allow to customize the Authentication prefix

### ISSUE THREAD

**Issue by gbarbaten** [hzlmn/aiohttp-jwt#76]
**Rationale:**
Despite it's much more commont to use Bearer as prefix in the Authentication header, some systems may use other prefixes.
An example is the default configuration of Django JWT package (this is our case, as we are doing a microservice that will be integrated with an existing platform based in this package).

**Description:**
Provide a param in the middleware to specify the authentication header prefix with a default value as Bearer (so it keeps the backward compatibility).

**Comment by hzlmn** [comment]
Hi, yep thought about it, certainly need to add. It is in my todo for 1.0 ) but PR are warmly welcome 😃

**Comment by hzlmn** [comment]
Closed in #77

**Comment by hzlmn** [comment]
Released in v0.0.3. Thanks for contribution.
