### ISSUE TITLE
how to allow special method like OPTIONS to pass middleware

### ISSUE THREAD

**Issue by AndyLee1024** [hzlmn/aiohttp-jwt#97]
Hi , develop.

 I use AJAX  crossdomain to access my api. but OPTIONS request was intercepted by aiohttp-jwt middleware. how can i make OPTIONS request pass it.

**Comment by hzlmn** [comment]
@AndyLee1024 Hi, currently it is not possible i will add support for it soon. As a workaround you can set `credential_required` property to False

**Comment by AndyLee1024** [comment]
THANK YOU ^_^

**Comment by ckkz-it** [comment]
Hi @hzlmn, I just want to give a reminder for you to implement support for preflight cors requests (when OPTIONS request is being proceeded). I had to write [this workaround](https://gist.github.com/ckkz-it/14ff3b91e0dfdee8f7ebecc8c73d2ddc) for my project to make it work for now.
I've created PR for you https://github.com/hzlmn/aiohttp-jwt/pull/139

**Comment by hzlmn** [comment]
Closed #139
